name: Bot - Stray Cat 2

on:
  #schedule:
  #  - cron: '30 1 * * *'
  #  - cron: '0 5 * * *'
  #  - cron: '30 10 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          
      - run: pip install tweepy
      
      - name: Run Stray Cat 2 Script
        env:
          # ใช้ Secret ชุด SC1 (Stray Cat 1)
          CONSUMER_KEY: ${{ secrets.SC2_CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.SC2_CONSUMER_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.SC2_X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.SC2_X_ACCESS_TOKEN_SECRET }}
        run: python Stray_cat_2_autopost_x.py
